Tsoro yematatu
GamesCrafters/GamesmanClassic pull request #70
Opened 2024-11-25 19:28 UTC by kenzhengjk

2024-11-26 21:36 UTC, michael-wsp requested changes
Looks good, I made a few comments for changes before we merge.

2024-11-26 21:36 UTC, michael-wsp commented on src/Makefile.in
> +			$(WINKERS_OBJ) $(WUZHI_OBJ) $(XIGUA_OBJ) $(TSOROYEMATATU_OBJ)
Let's move this so it remains in alphabetical order

2024-11-26 21:36 UTC, michael-wsp commented on src/Makefile.in
> +			$(WINKERS_EXE) $(WUZHI_EXE) $(XIGUA_EXE) $(TSOROYEMATATU_EXE)
Same here, move to correct alphabetical spot.

2024-11-26 21:36 UTC, michael-wsp commented on src/mtsoroyematatu.c
> +POSITION gNumberOfPositions = 6561; // > 3^7
Since it's here, update the comment to be 3^8 (since we added the turn encoding to the position).

2024-11-26 21:36 UTC, michael-wsp commented on src/mtsoroyematatu.c
> +int g3Array[] = {1, 3, 9, 27, 81, 243, 729};
I think we can safely remove this, is not being used for the hashing anymore.

2024-11-26 21:36 UTC, michael-wsp commented on src/mtsoroyematatu.c
> +        printf("%8s's move: ", playerName);
I think this is where the player's move is prompted, so try editing this to make it properly align with the printed board representation above.

2024-11-28 03:35 UTC, michael-wsp approved these changes
Looks good!

2024-12-04 21:47 UTC, aqitya commented
congrats are completing "the tantalizing game of tsoroyematatu" =]. Go ahead and merge the 3 PRs whenever!

2024-12-05 04:57 UTC, merged